version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=main
      - POSTGRES_USER=main
      - POSTGRES_DB=SyL
  spring-server:
    image: eclipse-temurin:17-jdk-focal
    build: 
      dockerfile: ./Dockerfile.spring-server
    volumes:
      - .:/app
    ports:
      - 8080:8080
      - 5432:5432
    # depends_on:
    # - postgres
    # links:
    # - "postgres:database"
